import { ThemeColors, ThemeName } from '../types/schema';

export const PALETTES: Record<ThemeName, ThemeColors> = {
  premium: {
    name: 'Premium Sapphire',
    primary: '#1E3A8A', // Deep Navy
    primaryDark: '#0F172A',
    secondary: '#3B82F6',
    accent: '#F59E0B', // Gold
    surface: '#FFFFFF',
    surfaceMuted: '#F8FAFC',
    border: '#E2E8F0',
    text: '#0F172A',
    textMuted: '#64748B',
    bannerBg: '1E3A8A',
    bannerText: 'FFFFFF',
    kpiBg: 'F0F7FF',
    kpiBorder: 'BFDBFE',
    headerBg: '1E3A8A',
    headerText: 'FFFFFF',
    zebraBg: 'F8FAFC',
    totalBg: 'EFF6FF',
  },
  midnight: {
    name: 'Midnight Onyx',
    primary: '#0F172A', // Slate Dark
    primaryDark: '#020617',
    secondary: '#06B6D4', // Cyan
    accent: '#38BDF8',
    surface: '#1E293B',
    surfaceMuted: '#0F172A',
    border: '#334155',
    text: '#F8FAFC',
    textMuted: '#94A3B8',
    bannerBg: '0F172A',
    bannerText: '38BDF8',
    kpiBg: '1E293B',
    kpiBorder: '334155',
    headerBg: '1E293B',
    headerText: '38BDF8',
    zebraBg: '0F172A',
    totalBg: '334155',
  },
  forest: {
    name: 'Forest Emerald',
    primary: '#064E3B', // Deep Forest Green
    primaryDark: '#022C22',
    secondary: '#10B981',
    accent: '#34D399',
    surface: '#FFFFFF',
    surfaceMuted: '#F0FDF4',
    border: '#DCFCE7',
    text: '#064E3B',
    textMuted: '#047857',
    bannerBg: '064E3B',
    bannerText: 'FFFFFF',
    kpiBg: 'ECFDF5',
    kpiBorder: 'A7F3D0',
    headerBg: '064E3B',
    headerText: 'FFFFFF',
    zebraBg: 'F0FDF4',
    totalBg: 'D1FAE5',
  },
  sunset: {
    name: 'Sunset Amber',
    primary: '#7C2D12', // Deep Amber Rust
    primaryDark: '#451A03',
    secondary: '#EA580C',
    accent: '#F97316',
    surface: '#FFFFFF',
    surfaceMuted: '#FFF7ED',
    border: '#FFEDD5',
    text: '#431407',
    textMuted: '#9A3412',
    bannerBg: '7C2D12',
    bannerText: 'FFFFFF',
    kpiBg: 'FFF7ED',
    kpiBorder: 'FED7AA',
    headerBg: '7C2D12',
    headerText: 'FFFFFF',
    zebraBg: 'FFFBF7',
    totalBg: 'FFEDD5',
  },
};
